### ISSUE TITLE
Failure to access a queue that belongs to another AWS account.

### ISSUE THREAD

**Issue by roboverall** [fabiogouw/spark-sqs-sink#2]
The databricks instance we are using belongs to one AWS account and the SQS queue that belongs to another AWS account. The cross account permissions created have been tested and we have established this is not the issue.

The failure is:

`com.amazonaws.services.sqs.model.QueueDoesNotExistException: The specified queue does not exist for this wsdl version. (Service: AmazonSQS; Status Code: 400; Error Code: AWS.SimpleQueueService.NonExistentQueue`.

[The issue seems to be with the GetQueueUrl method](https://github.com/fabiogouw/spark-aws-messaging/blob/1b6c6f6ff9e5dfb12c299df8938a54666edc1656/spark-aws-messaging/src/main/java/com/fabiogouw/spark/awsmessaging/sqs/SQSSinkDataWriter.java#L40)

Could the following parameter "QueueOwnerAWSAccountId" for the [GetQueueUrl method](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_GetQueueUrl.html) be made available?

**Comment by fabiogouw** [comment]
Thanks for your contribution, the changes have been released in the 0.4.0 version of this lib!
