### ISSUE TITLE
Upgrade to spark 3.3.2

### ISSUE THREAD

**Issue by danbaron63** [fabiogouw/spark-sqs-sink#20]
We're using this library with databricks spark jobs which has worked fine until now, however, we have a requirement to upgrade our  spark jobs to [Databricks Runtime 12.2](https://docs.databricks.com/en/release-notes/runtime/index.html#supported-databricks-runtime-lts-releases) to take advantage of newer features. This comes with spark 3.3.2 which is no longer compatible with this library.

We therefore require that this library be upgraded to work with Spark 3.3.2. If I get time I'll send over a PR, however, if anyone is able to do it first then that would be a huge help!

Thanks!

**Comment by fabiogouw** [comment]
@danbaron63 , please use the version 1.1.1 of this library, it's been updated to use Spark 3.3.2. Any issues, let me know. Thanks.
